name: lib_flutter_app
description: Library for Flutter applications
version: 1.1.0
homepage: https://www.diagro.be
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.10.1"

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  http: ^0.13.4
  flutter_dotenv: ^5.0.2
  provider: ^6.0.1
  google_fonts: ^2.3.1
  flutter_riverpod: ^1.0.0
  permission_handler: ^8.3.0
  external_path: ^1.0.1
  connectivity_plus: ^2.1.0
  line_icons: ^2.0.1
  intl: ^0.17.0
  badges: ^2.0.2
  adaptive_dialog: ^1.3.0
  loading_animation_widget: ^1.1.0+2
  lib_flutter_token:
    git:
      url: https://github.com/diagro-git/lib_flutter_token.git
      ref: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  hive_generator: ^1.1.1
  build_runner: ^2.1.5

# The following section is specific to Flutter.
flutter:

  assets:
    - assets/bg.jpg
