name: lib_flutter_app
description: Library for Flutter applications
version: 1.8.1
homepage: https://www.diagro.be
publish_to: none

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  adaptive_dialog: ^1.3.0
  app_tracking_transparency: ^2.0.2+1
  android_id: ^0.0.7
  connectivity_plus: ^2.1.0
  badges: ^2.0.2
  device_info_plus: ^4.1.0
  external_path: ^1.0.1
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  flutter_riverpod: ^1.0.0
  google_fonts: ^3.0.1
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  http: ^0.13.4
  intl: ^0.17.0
  lib_flutter_token:
    git:
      url: https://github.com/diagro-git/lib_flutter_token.git
      ref: ^1.1.0
  line_icons: ^2.0.1
  loading_animation_widget: ^1.1.0+2
  provider: ^6.0.1
  permission_handler: ^10.0.0

dev_dependencies:
  build_runner: ^2.1.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  hive_generator: ^1.1.1

# The following section is specific to Flutter.
flutter:
  assets:
    - assets/bg.jpg
